#!/usr/bin/env python3
"""Demo inputs for the minisite, cut from the project's own stimulus
(test_audio/stimulus/02_hits.wav: snare and rim one-shots, generated by
tools/make_stimulus.py). No recordings of anything else."""
import struct, sys, wave

SR = 48000
STIM = sys.argv[1]   # test_audio/stimulus
OUT = sys.argv[2]    # scratch dir


def read24(path):
    w = wave.open(path)
    assert w.getsampwidth() == 3 and w.getnchannels() == 1 and w.getframerate() == SR
    raw = w.readframes(w.getnframes())
    out = []
    for i in range(0, len(raw), 3):
        v = raw[i] | (raw[i + 1] << 8) | (raw[i + 2] << 16)
        if v & 0x800000:
            v -= 1 << 24
        out.append(v / 8388608.0)
    return out


def write24(path, x):
    w = wave.open(path, "wb")
    w.setnchannels(1); w.setsampwidth(3); w.setframerate(SR)
    b = bytearray()
    for s in x:
        v = max(-8388608, min(8388607, int(round(s * 8388607))))
        b += struct.pack("<i", v)[:3]
    w.writeframes(bytes(b))


hits = read24(f"{STIM}/02_hits.wav")
def cut(t0, dur):
    a = int(t0 * SR)
    return hits[a:a + int(dur * SR)]

snare = cut(1.0, 0.25)        # snare at -6 dBFS
rim_mid = cut(25.0, 0.06)     # rim at -12 dBFS
rim_ghost = cut(31.0, 0.06)   # rim at -18 dBFS


def place(buf, hit, t):
    a = int(round(t * SR))
    for i, s in enumerate(hit):
        if a + i < len(buf):
            buf[a + i] += s


# A one-drop groove at 75 bpm (beat 0.8 s): the snare on beat 3, a rim on
# the offbeats of 2 and 4, ghost rims on a few sixteenths. 4 bars + tail.
BEAT = 0.8
PRE = 0.4
def groove(bars, tail):
    buf = [0.0] * int((PRE + bars * 4 * BEAT + tail) * SR)
    for bar in range(bars):
        t = PRE + bar * 4 * BEAT
        place(buf, snare, t + 2 * BEAT)
        place(buf, rim_mid, t + 1.5 * BEAT)
        place(buf, rim_mid, t + 3.5 * BEAT)
        for g in (0.75, 2.75, 3.25):
            place(buf, rim_ghost, t + g * BEAT)
    return buf

write24(f"{OUT}/groove.wav", groove(4, 5.0))
# The snare on its own: 0.4 s in, then room for the tail.
one = [0.0] * int(9.0 * SR); place(one, snare, PRE)
write24(f"{OUT}/snare_one.wav", one)
print("groove: snare at", [PRE + b * 4 * BEAT + 2 * BEAT for b in range(4)])

# A long snare: one hit, then 17.6 s for the Howl to build and fall away.
howl = [0.0] * int(18.0 * SR); place(howl, snare, PRE)
write24(f"{OUT}/snare_long.wav", howl)
# The skank (Am-D offbeat stabs, 75 bpm) with 1.6 s more lead-in, so a
# 75 bpm clock from t = 0 has set the echo's tempo before the first chord.
sk = [0.0] * int(1.6 * SR) + read24(f"{STIM}/04_skank.wav")
write24(f"{OUT}/skank_clocked.wav", sk[: int(20.0 * SR)])
# The C minor pad, cut at 8 s with a 0.5 s fade, then silence to 20 s:
# the Hold demo (the bed rings on after the chord stops).
pad = read24(f"{STIM}/10_pad_cminor.wav")
a, b = int(7.5 * SR), int(8.0 * SR)
padcut = pad[:a] + [s * (1 - (i - a) / (b - a)) for i, s in enumerate(pad[a:b], start=a)]
padcut += [0.0] * (int(20.0 * SR) - len(padcut))
write24(f"{OUT}/pad_then_silence.wav", padcut)
write24(f"{OUT}/pad.wav", pad[: int(15.0 * SR)])
