#!/usr/bin/env python3
"""Draw the Versio panel with Resilio's current control mapping, for
deciding a remap (which knob does what) before a custom panel exists.

Geometry comes from tools/make_panel_svg.py (NE's official template).
Functions and the pot -> libDaisy knob order mirror the release firmware
(firmware/main.cpp kPotParams / kPotKnob, ADR 0028). The pot order was
measured at the M0 LED check (29 Sep 2026); SW_0 = top toggle = SPRINGS,
SW_1 = ATTITUDE; button + gate = Kick.

Usage: python3 tools/make_panel_mapping_svg.py [out.svg]
Default output: docs/panel/versio_panel_current_mapping.svg. Stdlib only.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_panel_svg import PANEL_W, PANEL_H, PARTS, f  # noqa: E402

KNOBS = {  # pot id -> (libDaisy knob index, function)
    "P1": ("K0", "MIX"), "P2": ("K4", "DECAY"), "P3": ("K2", "TONE"),
    "P4": ("K1", "SPLASH"), "P5": ("K5", "TENSION"), "P6": ("K3", "WOBBLE"),
    "P7": ("K6", "DRIVE"),
}
TOGGLES = {"SW1": ("SW_0", "SPRINGS", "1 · 2 · 3 (left→right)"), "SW2": ("SW_1", "ATTITUDE", "CLN·DRV·KCK")}
LEDS = {"LED1": "clip", "LED2": "wet", "LED3": "springs", "LED4": "attitude"}
SCALE = 8  # px per mm for the default on-screen size


def build():
    out = []
    a = out.append
    a('<?xml version="1.0" encoding="UTF-8"?>')
    a(f'<svg xmlns="http://www.w3.org/2000/svg" width="{f(PANEL_W * SCALE)}" height="{f(PANEL_H * SCALE)}" '
      f'viewBox="0 0 {f(PANEL_W)} {f(PANEL_H)}">')
    a('  <title>Resilio Versio: current control mapping</title>')
    a('  <desc>Noise Engineering Versio panel (NE template geometry) labelled with Resilio\'s current '
      'firmware mapping. Pot/switch/LED ids (P1-P7, SW1-SW2, LED1-LED4, J1-J12) are for naming a remap. '
      'Generated by tools/make_panel_mapping_svg.py.</desc>')
    a('  <style>'
      'text{font-family:Helvetica,Arial,sans-serif}'
      '.panel{fill:#f4f2ee;stroke:#1a1a1a;stroke-width:0.25}'
      '.pot{fill:#2b2b2b;stroke:#000;stroke-width:0.2}'
      '.potring{fill:none;stroke:#9a9a9a;stroke-width:0.12;stroke-dasharray:0.6 0.4}'
      '.id{font-size:2.6px;font-weight:700;fill:#ffffff}'
      '.fn{font-size:2.3px;font-weight:700;fill:#1a1a1a}'
      '.idx{font-size:1.5px;fill:#6b6b6b}'
      '.sid{font-size:1.9px;font-weight:700;fill:#c2410c}'
      '.small{font-size:1.45px;fill:#444}'
      '.tog{fill:#cfcfcf;stroke:#333;stroke-width:0.15}'
      '.led{fill:#e8e8e8;stroke:#333;stroke-width:0.12}'
      '.jack{fill:#d9d9d9;stroke:#333;stroke-width:0.15}'
      '.jackhole{fill:#1a1a1a}'
      '.mount{fill:none;stroke:#999;stroke-width:0.12}'
      '.note{font-size:1.35px;fill:#555}'
      '</style>')
    a(f'  <rect class="panel" x="0" y="0" width="{f(PANEL_W)}" height="{f(PANEL_H)}" rx="0.6"/>')
    a(f'  <text class="fn" x="{f(PANEL_W / 2)}" y="8.6" text-anchor="middle" font-size="2.6px">RESILIO · panel map</text>')

    for pid, kind, cx, cy, d in PARTS:
        if kind == "mounting":
            a(f'  <circle class="mount" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2)}"/>')
        elif kind == "pot":
            idx, fn = KNOBS[pid]
            r = d / 2 + 1.3  # knob cap, roughly
            a(f'  <circle class="potring" cx="{f(cx)}" cy="{f(cy)}" r="{f(r + 0.9)}"/>')
            a(f'  <circle class="pot" cx="{f(cx)}" cy="{f(cy)}" r="{f(r)}"/>')
            a(f'  <text class="id" x="{f(cx)}" y="{f(cy + 0.9)}" text-anchor="middle">{pid}</text>')
            if pid == "P6":  # the toggles' labels sit below it: one line above instead
                a(f'  <text class="fn" x="{f(cx)}" y="{f(cy - r - 1.3)}" text-anchor="middle">{fn} '
                  f'<tspan class="idx" font-weight="400">{idx}</tspan></text>')
            else:
                a(f'  <text class="fn" x="{f(cx)}" y="{f(cy + r + 3.1)}" text-anchor="middle">{fn}</text>')
                a(f'  <text class="idx" x="{f(cx)}" y="{f(cy + r + 4.8)}" text-anchor="middle">{idx}</text>')
        elif kind == "toggle":
            idx, fn, pos = TOGGLES[pid]
            a(f'  <circle class="tog" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2)}"/>')
            a(f'  <text class="sid" x="{f(cx + d / 2 + 0.8)}" y="{f(cy - 0.3)}">{pid} {fn}</text>')
            a(f'  <text class="small" x="{f(cx + d / 2 + 0.8)}" y="{f(cy + 1.7)}">{pos}</text>')
        elif kind == "button":
            a(f'  <circle class="tog" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2)}"/>')
            a(f'  <text class="sid" x="{f(cx + d / 2 + 0.8)}" y="{f(cy - 0.3)}">BTN KICK</text>')
            a(f'  <text class="small" x="{f(cx + d / 2 + 0.8)}" y="{f(cy + 1.7)}">(also gate in)</text>')
        elif kind == "led":
            a(f'  <circle class="led" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2)}"/>')
            a(f'  <text class="sid" x="{f(cx)}" y="{f(cy - 2.3)}" text-anchor="middle" font-size="1.5px">L{pid[-1]}</text>')
            dy = 5.9 if pid in ("LED2", "LED4") else 4.2  # above the ids, staggered (5 mm apart)
            a(f'  <text class="small" x="{f(cx)}" y="{f(cy - dy)}" text-anchor="middle" font-size="1.2px">{LEDS[pid]}</text>')
        elif kind == "jack":
            a(f'  <circle class="jack" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2 + 0.9)}"/>')
            a(f'  <circle class="jackhole" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2 - 1.2)}"/>')
            a(f'  <text class="sid" x="{f(cx)}" y="{f(cy + d / 2 + 3.0)}" text-anchor="middle" font-size="1.6px">{pid}</text>')

    y = 75.6  # the free band between the button and the jacks
    for line in ("K = libDaisy knob index (measured at M0; not reading order).",
                 "Each knob's CV input follows its knob."):
        a(f'  <text class="note" x="{f(PANEL_W / 2)}" y="{f(y)}" text-anchor="middle">{line}</text>')
        y += 1.8
    a('</svg>')
    return "\n".join(out) + "\n"


def main():
    root = Path(__file__).resolve().parent.parent
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else root / "docs" / "panel" / "versio_panel_current_mapping.svg"
    out.write_text(build())
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
