#!/usr/bin/env python3
"""Generate an accurate Noise Engineering Versio front-panel template (SVG).

Source of every coordinate: Noise Engineering's official "Printable Panels"
download (versio_panel.svg inside versio_printable_*.zip), linked from
https://noiseengineering.us/pages/world-of-versio/ . NE's file places all
circles inside one <g transform="scale(1,-1)">, so each part's distance from
the TOP edge is abs(cy). Values below are NE's numbers, unrounded apart from
float noise, in millimetres. The file gives hole geometry only; the clearance
rings are a design guide (hole edge + CLEARANCE_MM), not measured part sizes.

Usage: python3 tools/make_panel_svg.py [out.svg]
Default output: docs/panel/versio_panel_template.svg, plus a coordinate table
docs/panel/versio_panel_coordinates.csv. Stdlib only.
"""

import csv
import sys
from pathlib import Path

PANEL_W = 50.5    # mm (10 HP, as cut; nominal 10 HP = 50.8)
PANEL_H = 128.5   # mm (3U)
HP = 5.08         # mm
CLEARANCE_MM = 1.5

# (id, kind, x, y_from_top, hole_diameter)
PARTS = [
    ("M1", "mounting", 7.649528054, 3.0014, 3.2),
    ("M2", "mounting", 43.209528054, 3.0014, 3.2),
    ("M3", "mounting", 7.649528054, 125.50115, 3.2),
    ("M4", "mounting", 43.209528054, 125.50115, 3.2),
    # Pots, top to bottom, left to right
    ("P1", "pot", 7.76999988555908, 18.530000305176, 9.0),
    ("P2", "pot", 43.3300003051758, 18.530000305176, 9.0),
    ("P3", "pot", 25.1689990997314, 28.6899963378906, 9.0),
    ("P4", "pot", 7.76999988555908, 39.4850021362305, 9.0),
    ("P5", "pot", 43.3300003051758, 39.4850021362305, 9.0),
    ("P6", "pot", 25.1689990997314, 49.3275009155273, 9.0),
    ("P7", "pot", 43.3300003051758, 60.4400001525879, 9.0),
    # LEDs, left to right
    ("LED1", "led", 17.2950004577637, 19.799996948242, 3.0),
    ("LED2", "led", 22.3750003814697, 19.799996948242, 3.0),
    ("LED3", "led", 29.3599990844727, 19.799996948242, 3.0),
    ("LED4", "led", 34.4400009155273, 19.799996948242, 3.0),
    # Toggles (3-position), top then bottom
    ("SW1", "toggle", 8.40500011444092, 57.8999992370605, 5.08),
    ("SW2", "toggle", 8.40500011444092, 67.4250007629395, 5.08),
    # Push button
    ("BTN", "button", 26.1849998474121, 69.3299995422363, 5.334),
]
JACK_X = [5.22999992370605, 18.5650009155273, 31.9, 44.6000007629395]
JACK_Y = [83.3000007629395, 97.2700000762939, 111.239999866486]
n = 1
for y in JACK_Y:
    for x in JACK_X:
        PARTS.append((f"J{n}", "jack", x, y, 6.8))
        n += 1

LAYERS = [
    ("jacks", "Jacks (12)"),
    ("pots", "Pots (7)"),
    ("toggles", "Toggle switches (2)"),
    ("button", "Push button"),
    ("leds", "LEDs (4)"),
    ("mounting", "Mounting holes (4)"),
]
KIND_TO_LAYER = {"jack": "jacks", "pot": "pots", "toggle": "toggles", "button": "button",
                 "led": "leds", "mounting": "mounting"}


def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def build_svg():
    out = []
    a = out.append
    a('<?xml version="1.0" encoding="UTF-8"?>')
    a(f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" '
      f'width="{f(PANEL_W)}mm" height="{f(PANEL_H)}mm" viewBox="0 0 {f(PANEL_W)} {f(PANEL_H)}">')
    a('  <title>Noise Engineering Versio panel template (10 HP)</title>')
    a('  <desc>1 unit = 1 mm. Hole positions and diameters from Noise Engineering\'s official printable panel '
      'template (versio_panel.svg, World of Versio). Clearance rings = hole edge + '
      f'{f(CLEARANCE_MM)} mm (design guide only). Generated by tools/make_panel_svg.py.</desc>')
    a('  <style>'
      '.outline{fill:#ffffff;stroke:#000000;stroke-width:0.2}'
      '.hole{fill:none;stroke:#e0002a;stroke-width:0.15}'
      '.keep{fill:none;stroke:#e0002a;stroke-width:0.08;stroke-dasharray:0.5 0.4;opacity:0.6}'
      '.cross{stroke:#0070f3;stroke-width:0.06}'
      '.grid{stroke:#00a0a0;stroke-width:0.05;opacity:0.35}'
      '.label{font-family:Helvetica,Arial,sans-serif;font-size:1.6px;fill:#0070f3}'
      '</style>')

    # Background / outline
    a('  <g id="panel" inkscape:groupmode="layer" inkscape:label="Panel outline">')
    a(f'    <rect class="outline" x="0" y="0" width="{f(PANEL_W)}" height="{f(PANEL_H)}"/>')
    a('  </g>')

    # HP guides (vertical lines every 5.08 mm from the left edge)
    a('  <g id="hp-guides" inkscape:groupmode="layer" inkscape:label="HP guides (5.08 mm)">')
    x = HP
    while x < PANEL_W:
        a(f'    <line class="grid" x1="{f(x)}" y1="0" x2="{f(x)}" y2="{f(PANEL_H)}"/>')
        x += HP
    a('  </g>')

    # Clearance rings (one layer, easy to hide)
    a('  <g id="clearance" inkscape:groupmode="layer" inkscape:label="Clearance guide (hole + 1.5 mm)">')
    for pid, kind, cx, cy, d in PARTS:
        if kind == "mounting":
            continue
        a(f'    <circle class="keep" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2 + CLEARANCE_MM)}"/>')
    a('  </g>')

    # Holes, one layer per component type
    for layer, label in LAYERS:
        a(f'  <g id="{layer}" inkscape:groupmode="layer" inkscape:label="{label}">')
        for pid, kind, cx, cy, d in PARTS:
            if KIND_TO_LAYER[kind] != layer:
                continue
            a(f'    <circle id="{pid}" class="hole" cx="{f(cx)}" cy="{f(cy)}" r="{f(d / 2)}"/>')
        a('  </g>')

    # Centre marks
    a('  <g id="centres" inkscape:groupmode="layer" inkscape:label="Centre marks">')
    for pid, kind, cx, cy, d in PARTS:
        s = min(1.2, d / 2)
        a(f'    <line class="cross" x1="{f(cx - s)}" y1="{f(cy)}" x2="{f(cx + s)}" y2="{f(cy)}"/>')
        a(f'    <line class="cross" x1="{f(cx)}" y1="{f(cy - s)}" x2="{f(cx)}" y2="{f(cy + s)}"/>')
    a('  </g>')

    # Labels (part IDs; see the coordinates CSV)
    a('  <g id="labels" inkscape:groupmode="layer" inkscape:label="Part labels">')
    for pid, kind, cx, cy, d in PARTS:
        if kind == "mounting":
            continue
        if kind == "led":  # LEDs sit close together: label below, centred
            a(f'    <text class="label" x="{f(cx)}" y="{f(cy + d / 2 + 2.0)}" text-anchor="middle">{pid[-1]}</text>')
        else:
            a(f'    <text class="label" x="{f(cx + d / 2 + 0.4)}" y="{f(cy - d / 2 - 0.2)}">{pid}</text>')
    a('  </g>')
    a('</svg>')
    return "\n".join(out) + "\n"


def main():
    repo = Path(__file__).resolve().parent.parent
    svg_path = Path(sys.argv[1]) if len(sys.argv) > 1 else repo / "docs" / "panel" / "versio_panel_template.svg"
    svg_path.parent.mkdir(parents=True, exist_ok=True)
    svg_path.write_text(build_svg())
    csv_path = svg_path.with_name("versio_panel_coordinates.csv")
    with csv_path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["id", "kind", "x_mm_from_left", "y_mm_from_top", "hole_diameter_mm"])
        for pid, kind, cx, cy, d in PARTS:
            w.writerow([pid, kind, f"{cx:.3f}", f"{cy:.3f}", f(d)])
    print(svg_path)
    print(csv_path)


if __name__ == "__main__":
    main()
